version: '3.3'

services:
  todo-api:
    build: ./
    command: ./wait-for-postgres.sh db ./todo-rest-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5436:5432"